import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

import ApiProvider from "@/providers/ApiProvider";
import MainFooter from "@/components/shared/MainFooter";
import WalletProvider from "@/providers/WalletProvider";
import { MainHeader } from "@/components/shared/MainHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning={true}>
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <WalletProvider>
            <ApiProvider>
            <MainHeader/>
            {children}
            <MainFooter/>
            </ApiProvider>
            </WalletProvider>
            
          
          </ThemeProvider>
      </body>
    </html>
  );
}
